version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_aws
    versions:
    - 2.1.7
    - 2.1.8
    - 2.1.9
    - 2.2.0
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
    - 3.7.0
    - 3.7.2
    - 3.7.3
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: excoveralls
    versions:
    - 0.13.4
- package-ecosystem: mix
  directory: "/apps/train_loc"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: timex
    versions:
    - 3.7.0
    - 3.7.2
    - 3.7.3
- package-ecosystem: mix
  directory: "/apps/commuter_rail_boarding"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
