name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev
    env:
      ECS_CLUSTER: commuter-rail-boarding
      ECS_SERVICE: commuter-rail-boarding-dev

    steps:
      - uses: actions/checkout@v2
