name: Change Task Count

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "dev or prod"
        required: true
      new_count:
        description: "1 to turn on 0 to turn off"
        required: true

jobs:
  set_count:
    if: |
      ( github.event.inputs.environment == 'prod' || github.event.inputs.environment == 'dev' ) &&
      ( github.event.inputs.new_count == 0 || github.event.inputs.new_count == 1)

    runs-on: ubuntu-latest

    steps:
      - name: run command
        run: aws ecs update-service --cluster lamp --service commuter-rail-boarding-${{ github.event.inputs.environment }} --desired-count ${{ github.event.inputs.new_count }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'